### ISSUE TITLE
Goal: rename TSN to Truf Network

### ISSUE THREAD

**Issue by zolotokrylin** [trufnetwork/docs#16]
# Problem
- [x] https://github.com/trufnetwork/truf-node-sdk-js/issues/19

_some naming has been renamed from tsn into truf on this goal: https://github.com/trufnetwork/truf-network/issues/29_
_I will check the whole repos to ensure all have been renamed 27-11-2024_

**Comment by MicBun** [comment]
What is the scope of this goal? Does it include: chain name, AWS configuration, etc?
